---
title: "Plotting Small Pelagic Surveys"
output: html_document
---

```{r setup, include=FALSE}
#library(devtools)
#install_github("https://github.com/rooperc4/ForageFishLitReview")

library(ForageFishLitReview)
library(openxlsx)
library(ggplot2)
library(sf)
library(rgdal)
library(proj4)
library(rnaturalearth)
library(gifski)
```


```{r seasonplots}
surveydata<-readWorkbook("SPF_surveys_110321.xlsx", sheet = "SurveysData")

seasons<-c("spring","summer","autumn","winter","all")
season2<-subset(surveydata,is.na(surveydata$Season)==FALSE)
season2<-pressure_table(seasons,season2$Season)#[is.na(surveydata$Season)==FALSE])
season2$Season<-factor(season2$pressure,levels=c("spring","summer","autumn","winter","all"),labels=c("Spring","Summer","Autumn","Winter","All"))
ggplot(season2)+geom_bar(aes(x=Season,y=count),stat="identity")+ylab("Frequency")+xlab("")

stages<-c("egg","larval","juvenile","adult")
stages2<-subset(surveydata,is.na(surveydata$Life_history_stages)==FALSE)
stages2<-pressure_table(stages,stages2$Life_history_stages)#[is.na(surveydata$Season)==FALSE])
stages2$Stages<-factor(stages2$pressure,levels=c("egg","larval","juvenile","adult"),labels=c("Egg","Larvae","Juvenile","Adult"))
ggplot(stages2)+geom_bar(aes(x=Stages,y=count,fill=Stages),stat="identity")+ylab("Frequency")+xlab("")

gear<-c("trawls","acoustics","seine","plankton nets","eDNA")

gears2<-subset(surveydata,is.na(surveydata$Gear)==FALSE)
gears2<-pressure_table(gear,gears2$Gear)#[is.na(surveydata$Season)==FALSE])
gears2$Gear<-factor(gears2$pressure,levels=c("trawls","acoustics","plankton nets","seine","eDNA"),labels=c("trawls","acoustics","plankton nets","seine","eDNA"))
ggplot(gears2)+geom_bar(aes(x=Gear,y=count,fill=Gear),stat="identity")+ylab("Frequency")+xlab("")+scale_fill_viridis_d()

png("seasons.png",height=6,width=6,units="in",res=300)
ggplot(season2)+geom_bar(aes(x=Season,y=count),stat="identity")+ylab("Frequency")+xlab("")
dev.off()

png("stages.png",height=6,width=6,units="in",res=300)
ggplot(stages2)+geom_bar(aes(x=Stages,y=count,fill=Stages),stat="identity")+ylab("Frequency")+xlab("")
dev.off()

png("gears.png",height=6,width=6,units="in",res=300)
ggplot(gears2)+geom_bar(aes(x=Gear,y=count,fill=Gear),stat="identity")+ylab("Frequency")+xlab("")+scale_fill_viridis_d()
dev.off()

```


```{r wordcloud}
require(wordcloud)
require(tm)
require(RColorBrewer)

species<-c(surveydata$Target_species,surveydata$Other_SPF)
species<-gsub("[\n]"," ",species)
species<-gsub("[_x00D_]"," ",species)
species<-species[is.na(species)==FALSE]

ap.corpus <- Corpus(VectorSource(species))
ap.corpus <- tm_map(ap.corpus, removePunctuation)
#ap.corpus<-tm_map(ap.corpus,content_transformer(removeSpecialChars))
ap.corpus <- tm_map(ap.corpus, content_transformer(tolower))
ap.corpus <- tm_map(ap.corpus, function(x) removeWords(x, stopwords("english")))

ap.tdm <- TermDocumentMatrix(ap.corpus)
ap.m <- as.matrix(ap.tdm)
ap.v <- sort(rowSums(ap.m),decreasing=TRUE)
ap.d <- data.frame(word = names(ap.v),freq=ap.v)
table(ap.d$freq)
pal2 <- brewer.pal(8,"Dark2")

wordcloud(ap.d$word,ap.d$freq, scale=c(4,1),min.freq=1,
          max.words=Inf, random.order=FALSE, rot.per=.15, colors=pal2)

png("wordcloud.png",height=6,width=6,units="in",res=300)
wordcloud(ap.d$word,ap.d$freq, scale=c(4,1),min.freq=1,
          max.words=Inf, random.order=FALSE, rot.per=.15, colors=pal2)
dev.off()

```
```{r mapit}


#IMPORT THE BASEMAP AND TRANSFORM TO A NICER PROJECTION FOR THE NORTH PACIFIC
bg = ne_countries(scale = "medium",  returnclass = "sf")

surveydata<-readWorkbook("SPF_surveys_110321.xlsx", sheet = "SurveysData")

data1<-aggregate(Timing~Longitude+Latitude+Ecoregion,data=surveydata,FUN="length") 

#PLOT THE ENTIRE TRAJECTORY WITH THE MAP AS THE BACKGROUND
p<-ggplot()+
  #basemap
  geom_sf(data = bg)+
#  coord_sf(xlim = range(data3$x, na.rm = TRUE), 
#           ylim = range(data3$y, na.rm = TRUE), 
#           expand = TRUE)+
  
  # lines and points

  geom_point(data = data1, 
             aes(x=Longitude,y=Latitude,group=Timing,fill=Timing),
             alpha = 0.7, shape=21, size = 2)+
  
  # formatting
  scale_fill_viridis_c(option = "inferno")+
  scale_color_viridis_c(option = "inferno")+
  scale_size_continuous(range = c(0.1,14))+
  labs(x=NULL, y=NULL, 
       fill = 'Ecoregion', 
       color = 'Ecoregion')+
  theme_dark()+
  theme(panel.grid = element_blank(),legend.position="bottom")+labs(fill="Surveys")
p

png("map.png",height=6,width=6,units="in",res=300)
p
dev.off()

```



```{r plots}

method<-c(surveydata$Gear)

aggregate(Season~Ecoregion,data=surveydata,FUN="length")
aggregate(Season~Gear,data=surveydata,FUN="length")

#IMPORT THE BASEMAP AND TRANSFORM TO A NICER PROJECTION FOR THE NORTH PACIFIC
bg = ne_countries(scale = "medium",  returnclass = "sf")

surveydata<-readWorkbook("SPF_surveys_110321.xlsx", sheet = "SurveysData")

data1<-aggregate(Timing~Longitude+Latitude+Ecoregion,data=surveydata,FUN="length") 

#PLOT THE ENTIRE TRAJECTORY WITH THE MAP AS THE BACKGROUND
p<-ggplot()+
  #basemap
  geom_sf(data = bg)+
#  coord_sf(xlim = range(data3$x, na.rm = TRUE), 
#           ylim = range(data3$y, na.rm = TRUE), 
#           expand = TRUE)+
  
  # lines and points

  geom_point(data = data1, 
             aes(x=Longitude,y=Latitude,group=Timing,fill=Timing),
             alpha = 0.7, shape=21, size = 2)+
  
  # formatting
  scale_fill_viridis_c(option = "inferno")+
  scale_color_viridis_c(option = "inferno")+
  scale_size_continuous(range = c(0.1,14))+
  labs(x=NULL, y=NULL, 
       fill = 'Ecoregion', 
       color = 'Ecoregion')+
  theme_dark()+
  theme(panel.grid = element_blank(),legend.position="bottom")+labs(fill="Surveys")
p

```